apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: by-homeassi-poi-gateway-app-dev
  annotations:
    argocd/app-name: by-homeassi-poi-gateway-app-dev
    backstage.io/kubernetes-id: by-homeassi-poi-gateway-app
    backstage.io/kubernetes-namespace: by-homeassi
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/by-homeassi-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/by-homeassi/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/by-homeassi/deployments/by-homeassi-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/by-homeassi-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/by-homeassi"
  system: workshop-system-by-homeassi
  providesApis:
    - gateway-api-by-homeassi
  consumesApis:
    - backend-api-by-homeassi
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-by-homeassi
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/by-homeassi"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-by-homeassi
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://by-homeassi-poi-gateway-app-by-homeassi.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh23-demo/by-homeassi-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/by-homeassi"
  system: workshop-system-by-homeassi
  definition:
    $text: https://github.com/rhdh23-demo/by-homeassi-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
